pipeline {
  agent any

  options {
    disableConcurrentBuilds()
    ansiColor('xterm')
  }
  
  triggers {
      cron('30 2 * * *')
  }

  environment {
    ARCHIVE_NAME = 'secrets'
    ARCHIVE_PATTERN = "${ARCHIVE_NAME}-*.tgz"
    GCLOUD_CREDENTIALS_ID ='<YOUR_CREDENTIALS_ID>'
    GCLOUD_BUCKET = '<YOUR_BUCKET_NAME>'
  }

  stages {
    stage('Pack secrets') {
      steps {
        sh '''
        cd ${JENKINS_HOME}
        VERSION_TIMESTAMP=$(date "+%Y%m%d-%H%M%S")

        # pack
        tar czvf ${ARCHIVE_NAME}-${VERSION_TIMESTAMP}.tgz secret* credentials.xml
        '''
      }
    }

    // stage('Upload secrets to GCS') {
    //   steps {
    //     step([$class: 'ClassicUploadStep', 
    //             credentialsId: env.GCLOUD_CREDENTIALS_ID,
    //             bucket: "gs://${env.GCLOUD_BUCKET}",
    //             pattern: env.ARCHIVE_PATTERN])
    //   }
    // }

    stage('Cleanup') {
      steps {
        sh 'rm -rf ${ARCHIVE_PATTERN}'
      }
    }
  }
}